POST http://localhost:4000/boyz-chat/signup
Content-Type: application/json

{
    "fullName":"Gavin Gonzalez",
    "username":"gavin_wowhillde",
    "email":"gavin323x5@gmail.com",
    "password":"bluezzgt"
}

